global using RoR2;
global using BepInEx;
global using BepInEx.Logging;
global using BepInEx.Configuration;
global using UnityEngine;
global using UnityEngine.Networking;
global using System.Collections;
global using System.Collections.Generic;
global using RiskOfOptions;